exclude = [
    ".git",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".ruff_cache",
    ".vscode",
    "lib/api/*",
    # TODO: maybe move the generated bindings to their own directory?
    "lib/backends/xcb.py",
    "lib/backends/waylandServer.py",
    "lib/backends/pango.py",
]

line-length = 88
indent-width = 4

target-version = "py313"

[lint]
# exclude = ["Q002", "Q001"]
select = ["E4", "E7", "E9", "F", "Q", "D300", "UP"]
flake8-quotes = {inline-quotes = "single", docstring-quotes="single", multiline-quotes="single"}

# unfixable = ["Q002", "Q001"]
fixable = ["ALL"]

[format]
exclude = ["Q002", "Q001"]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

